### ISSUE TITLE
Add instructions in the documentation on how to use the application

### ISSUE THREAD

**Issue by HTSagara** [mulla028/PolyglotCode#1]
### Summary:
The current documentation needs to provide enough instructions on how to use the application from the command line. 
I missed instructions for installing, running, and using.

### Suggested Documentation Sections:
1. **Installation**:
   - How to build the project using Maven.
   - How to install and run the application.

2. **Usage**:
   - The current version of the app presents the commands `polyglot <filename> <language>`. However, the user might get the error `zsh: command not found: polyglot` because the `polyglot` command needs to be globally installed. Otherwise, the user needs to run `mvn clean package` then java -jar target/PolyglotCode-1.0-SNAPSHOT-shaded.jar <filename> <language>` .
   - Check the issue [Issue #3](https://github.com/mulla028/PolyglotCode/issues/3)

3. **Examples**:
   - Add a section with several examples of running the application with different files and language options, including handling both existing and non-existent files.

### Expected Outcome:
- The documentation could provide clear, step-by-step instructions on how to install, run, and use the application.
- Users need understand how to pass arguments, handle errors, and know the available options.

**Comment by mulla028** [comment]
Very good point, sorry for providing you the app without good documentation. Looking forward to work with you in the future!
Fixed
