### ISSUE TITLE
Implement -v/--version and -h/--help flags for command-line usage

### ISSUE THREAD

**Issue by HTSagara** [mulla028/PolyglotCode#2]
### Summary
Check the version of the tool and get helpful usage information via the command-line flags `-v/--version` and `-h/--help`.

### Tasks:
1. **Implement the `-v/--version` flag:**
   - When a user runs the application with `-v` or `--version`, the application should print the name of the tool and its version (e.g., "PolyglotCode Release 0.1").
   - The program should exit after displaying the version.

2. **Implement the `-h/--help` flag:**
   - When a user runs the application with `-h` or `--help`, the application should display a help message with usage information.
   - The help message should explain the basic usage (`polyglot <filename> <language>`), and options for `-v/--version` and `-h/--help`.
   - The help message could include additional useful information, such as the location of example files (`examples` folder) and supported languages.

**Comment by mulla028** [comment]
Thank you! Fixed
