### ISSUE TITLE
Document how to make the polyglot command globally accessible or run the application manually

### ISSUE THREAD

**Issue by HTSagara** [mulla028/PolyglotCode#3]
### Summary:
Currently, the `polyglot` command is not available globally by default. Users need to either globally install the application or manually run the JAR file. The documentation should explain both options clearly.

### Suggested Documentation Sections:

1. **Option 1: Making `polyglot` Globally Accessible**:
   Provide instructions on how to set up the `polyglot` command so that it can be run from any directory in the terminal.

   - **Step 1**: Build the JAR file using Maven:
     ```bash
     mvn clean package
     ```
   - **Step 2**: Move the JAR file to a known directory (e.g., `/usr/local/bin`):
     ```bash
     sudo mv target/PolyglotCode-1.0-SNAPSHOT-shaded.jar /usr/local/bin/
     ```
   - **Step 3**: Create a symbolic link:
     ```bash
     sudo ln -s /usr/local/bin/PolyglotCode-1.0-SNAPSHOT-shaded.jar /usr/local/bin/polyglot
     ```
   - Now, the `polyglot` command can be used globally:
     ```bash
     polyglot <filename> <language>
     ```

2. **Option 2: Running the Application Manually**:
   If the user doesn't want to globally install the application, they can run the JAR file manually from the project directory:
   - **Step 1**: Build the JAR file using Maven:
     ```bash
     mvn clean package
     ```
   - **Step 2**: Run the application using the following command:
     ```bash
     java -jar target/PolyglotCode-1.0-SNAPSHOT-shaded.jar <filename> <language>
     ```

3. **Global Installation Script (Optional)**:
   Provide an optional shell script for users who want to quickly set up the global installation:
   ```bash
   #!/bin/bash
   sudo mv target/PolyglotCode-1.0-SNAPSHOT-shaded.jar /usr/local/bin/
   sudo ln -s /usr/local/bin/PolyglotCode-1.0-SNAPSHOT-shaded.jar /usr/local/bin/polyglot
   echo "Polyglot has been installed globally as the 'polyglot' command."

**Comment by mulla028** [comment]
Thank you so much! Added clear documentation in one of the recent commits!
Good point!
