### ISSUE TITLE
Handle unexpected output when file is missing but translation still occurs

### ISSUE THREAD

**Issue by HTSagara** [mulla028/PolyglotCode#4]
### Summary:
When attempting to run the application with a non-existent file, the program correctly outputs `File doesn't exist`, but it still performs a translation with unexpected content. This might cause confusion for users, as they expect the program to halt when the file isn't found.

### Steps to Reproduce:
1. Run the following command with a non-existent file:
   ```bash
   java -jar target/PolyglotCode-1.0-SNAPSHOT-shaded.jar invalidFile.txt French
 
2. Observe the following output:
- The program prints `File doesn't exist`, but it proceeds to print a translation result.
![Screenshot 2024-09-11 at 11 14 28 AM](https://github.com/user-attachments/assets/5ead7de1-07c1-4046-a3a4-41a0a568c332)

**Comment by mulla028** [comment]
You are right! I definitely must fix it !

**Comment by mulla028** [comment]
Thank you so much! Fixed it in recent commitment!
