### ISSUE TITLE
[Feature] Option -t to display token information

### ISSUE THREAD

**Issue by theoforger** [mulla028/PolyglotCode#5]
### Description
Add a `-t` or `--token-usage` option. When the program is run with this option, display additional information about token usage.

Would love to work on this issue myself. Feel free to assign me.

### Feature Checklist
- Support `-t` option
- From the API response, read token information under the `usage` object
- Output to `stderr`
- Update help information to include this option
- Update README

### Sample Output

```bash
# Existing Output... #
----------------------------------
Completion Tokens: 17
Prompt Tokens: 57
Total Tokens: 74
```

**Comment by mulla028** [comment]
Make sure to follow the expected output
