### ISSUE TITLE
[Feature] Support for a TOML config file

### ISSUE THREAD

**Issue by theoforger** [mulla028/PolyglotCode#9]
### Description
Currently the project supports options like `-a` to specify API key, and `-u` to specify base URL. However, there's no way to change the default without modifying the code itself and rebuild.

This issue proposes a feature to support a TOML config file, in which the users can set their preferred default.

### Expected Behavoir
- The program attempts to read the config file
- If the file exists, parse it. Otherwise do nothing
- If the file can't be parsed as TOML, show error
- If any option is overridden by an argument, use the argument instead. Otherwise, use the config file content

I'd love to work on this issue myself and submit a PR for it👍

**Comment by mulla028** [comment]
Thank you for the detailed explanation!
Feel free to ask questions 🗣️ 
Good luck 🍀
